### ISSUE TITLE
grub2-mkconfig fails using tumbleweed xfce live usb installer

### ISSUE THREAD

**Issue by ITwrx** [openSUSE/installation-images#339]
i'm not sure exactly which snapshot, but i probably used 2019101-6 or 2019100-9 or both. I tried both xfce and generic desktop system roles and they both fail with grub2-mkconfig unable to run. The net installer ended up working fine. I don't remember if i tried the standard dvd installer image or not. It may have this problem too. I was using a ssd that was of questionable reliability so i wasn't sure it was actually a software issue at first.

![xfce_install_fail](https://user-images.githubusercontent.com/1002762/67292989-699c1d80-f4a9-11e9-8869-2951653bd26d.png)

**Comment by wfeldt** [comment]
That looks like a package dependency issue but is not at all related to installation-images.

Could you please open a bug at https://bugzilla.opensuse.org? There's nothing I can do here.

**Comment by ITwrx** [comment]
ok, sure. i wasn't sure which repo and i thought bugzilla might be being phased out, seeing these repos on github. 

"not at all related to installation-images" seems a little specific/narrowly defined from an outsider's perspective. i mean this *is* an issue with the bootloader for a particular installation image, so it's at least *kind of* related...the readme for this repo doesn't exactly lead me to believe otherwise either. i did scan it before reporting here, and i still didn't get why it wouldn't be the right place to report.

Further clarification on these points in the readme might save you some aggravation.

thanks

**Comment by wfeldt** [comment]
I wasn't implying that you 'should have known better'. It's just that the people that will be working on the issue you reported will not look here **at all**. A report at bugzilla, component 'Installer', is the best way for this.
