### ISSUE TITLE
Missing /proc in chroot

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/installation-images#417]
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:C/installation-images:openSUSE/standard/x86_64
[  179s] adding package ca-certificates-mozilla [2.42-4.2.noarch] {postin,postun}
[  179s] running "cp -a /etc/ssl etc"
[  179s] running "cp -a /var/lib/ca-certificates var/lib"
[  179s] cp: setting permissions for 'var/lib/ca-certificates/openssl': Operation not supported
[  179s] cp: setting permissions for 'var/lib/ca-certificates/pem': Operation not supported
[  179s] mk_image: execution of "cp -a /var/lib/ca-certificates var/lib" failed at lib/AddFiles.pm line 796 in data/initrd/initrd.file_list line 587.

This is due to /proc missing in the chroot, which breaks lchmod.

**Comment by wfeldt** [comment]
solved with https://github.com/openSUSE/installation-images/pull/427

**Comment by marxin** [comment]
Thank you for the fix. When can I expect a submit request of the openSUSE package into `openSUSE:Factory`?

**Comment by wfeldt** [comment]
If you review the pr we can go ahead.
