### ISSUE TITLE
Tumbleweed/ MicroOS/ Kubic aarch64 and ppc64le build unresolvable

### ISSUE THREAD

**Issue by ventulis** [openSUSE/installation-images#522]
There have been no new Tumbleweed/ MicroOS/ Kubic images for `aarch64` and `ppc64le` since Snapshot [20210901](https://download.opensuse.org/ports/aarch64/tumbleweed/iso/Changes.20210901.txt). 
[According to Openbuild](https://build.opensuse.org/package/show/system:install:head/installation-images) it is

> **unresolvable**: nothing provides wallpaper-branding = 84.87.20200106 needed by [desktop-data-openSUSE](https://build.opensuse.org/package/show/openSUSE:Factory/desktop-data-openSUSE), (got version 84.87.20210910 provided by wallpaper-branding-openSUSE)

<details>
<summary>Screenshot</summary>

![Screenshot 2021-09-14 at 16-32-14 Installation Image Files](https://user-images.githubusercontent.com/72085617/133290482-5b361b16-8e4b-49fa-ac4f-b7f564306657.png)
</details>

**Comment by DimStar77** [comment]
This issue was outside of the responsibility for installation-images and has since been fixed

![image](https://github.com/openSUSE/installation-images/assets/532559/c1c16346-45c0-45c6-9e98-e8091187a923)
