### ISSUE TITLE
`~/.oscrc` -> `~/.config/osc/oscrc`

### ISSUE THREAD

**Issue by tacerus** [openSUSE/installation-images#553]
Hi,

it looks like my installations of `osc` places the user configuration file in `~/.config/osc/oscrc` instead of `~/.oscrc` - I had to install a symlink to make the make-process continue.
The article https://en.opensuse.org/openSUSE:OSC#Authentication suggests this is normal behavior for new installations/versions of `osc`.

I will attach a PR adding support for the new file location, but decided to open this issue along with it, in case my submitted patch is not the correct way to go.

Best,
Georg

**Comment by wfeldt** [comment]
I've merged the pull request.
