### ISSUE TITLE
powerpc images not signed

### ISSUE THREAD

**Issue by hramrach** [openSUSE/installation-images#575]
This is the signed image:

rpm -ql grub2-powerpc-ieee1275 | grep grub.elf
/usr/share/grub2/powerpc-ieee1275/grub.elf

WTF is this: https://github.com/openSUSE/installation-images/blob/63a0765e8f4f5a55c60864b1a86064f30301ed52/bin/mk_ppc_installation-images_bootbinaries.sh#L37

cp -apfv $bdir/grub2-ieee1275/grub2-ieee1275 $CD1/boot/$ARCH

where does the doubly nested directory come from?

**Comment by wfeldt** [comment]
see https://github.com/openSUSE/installation-images/pull/576
