### ISSUE TITLE
mount-rootfs-and-do-chroot does not mount efivarfs

### ISSUE THREAD

**Issue by olafhering** [openSUSE/installation-images#631]
`mount-rootfs-and-do-chroot.sh` does a bind mount for various filesystems into the chroot.
At least with current Tumbleweed `efibootmgr` can not be used in the chroot because `efivarfs` is not available.
I suggest to add the relevant mount point to the list of bind mounts.

**Comment by wfeldt** [comment]
fixed

**Comment by olafhering** [comment]
Thanks, please consider backport to SLE15.
